import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { type ReactNode, Suspense } from 'react';

import { ThemeProvider } from '@/lib/ui/components/shared/theme-provider';

// eslint-disable-next-line local/const-screaming-case-only
const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
// eslint-disable-next-line local/const-screaming-case-only
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export let metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          enableColorScheme
          enableSystem
          disableTransitionOnChange
          storageKey={'learning-portal.theme'}
          attribute={'class'}
        >
          <Suspense>{children}</Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
